### ISSUE TITLE
Sending notifications in real-time

### ISSUE THREAD

**Issue by Alexey-ebi** [cnr-ibba/IMAGE-InjectTool#19]
**Is your feature request related to a problem? Please describe.**
Send notifications in real-time

**Describe the solution you'd like**
Send messages using django-channels

**Describe alternatives you've considered**
Automatic page reload

- [x] Send notification messages using django-channels

- [x] Add documentation about django-channels using sphinx

**Comment by bunop** [comment]
@Alexey-ebi, will this issue related to #15? Why using channels to send n of animal and samples? they will remain the same, and actually they are calculated in real time:
```
<tr class="table-primary">
      <th scope="row">N. of Animals</th>
      <td>
        {{ validation_summary.n_animals }}
        {% if validation_summary.n_animal_issues %}
          ({{ validation_summary.n_animal_issues }} with issues in validation)
        {% endif %}
        {% if validation_summary.n_animal_unknown %}
          ({{ validation_summary.n_animal_unknown }} with unknown validation )
        {% endif %}
      </td>
    </tr>
```
![n_of_animals](https://user-images.githubusercontent.com/5947792/58707252-a0677f00-83b4-11e9-8f2d-d54eb56e2b03.png)

We have a perfomance issue since I calulate a validation report using python RE and this is not performant. Moreover, @wizardfan has added column info on validation and so `validation.models` and `validation.helpers` could be refactored. Will be better to model the validation report in a new static page and calculate this stuff once after validation?

**Comment by Alexey-ebi** [comment]
Ok, agree, all validation stuff will go in another issue

**Comment by bunop** [comment]
Ty @Alexey-ebi ! if you have doubts and you need to contact me, we could also using skype chat. As you prefer
