### ISSUE TITLE
Submit VCF files

### ISSUE THREAD

**Issue by robingarcia** [cnr-ibba/IMAGE-InjectTool#95]
My group is part of the IMAGE project and we have to publish VCF files either on IMAGE or on EVA. 
In the help of IMAGE I found, that IMAGE Injection tool is also using EVA [https://www.image2020genebank.eu/help](https://www.image2020genebank.eu/help) 
So, it is possible to submit VCF files via the IMAGE injection tool?
We only found three methods in order to submit data to IMAGE. 

We need the feature to upload/submit VCF files via the IMAGE injection tool. 

Otherwise we would submit our VCF files to EVA directly.

**Comment by bunop** [comment]
Dear @robingarcia,

Thank you for your interest into InjectTool and IMAGE project. You can't submit directly a `VCF` file into *EVA* with InjectTool. As described in [How to submit IMAGE genotype data.pdf](https://github.com/cnr-ibba/IMAGE-genotype/blob/master/How%20to%20submit%20IMAGE%20genotype%20data.pdf) in [IMAGE-genotype](https://github.com/cnr-ibba/IMAGE-genotype) folder, in order to submit genotype data compliant to IMAGE project data must:

- Meet the [IMAGE-metadata](https://github.com/cnr-ibba/IMAGE-metadata) standard
- Have been submitted to [BioSamples](https://www.ebi.ac.uk/biosamples/) using InjectTool

InjectTool can help you to validate your data against *IMAGE metatdata* and during submission to *BioSamples*. After uploading your data into BioSamples, you could export the `BioSamples IDs` from InjectTool and use them in your submission. The most important thing is that the **Project Title** used in *EVA* submission **must always** start with `IMAGE project: ` otherwise your data will not be automatically loaded into [IMAGE data portal](https://www.image2020genebank.eu/)

 For more information, please see [How to submit IMAGE genotype data.pdf](https://github.com/cnr-ibba/IMAGE-genotype/blob/master/How%20to%20submit%20IMAGE%20genotype%20data.pdf) guide and [EVA submit guide](https://www.ebi.ac.uk/eva/?Submit-Data)
