### ISSUE TITLE
Upload the template file xlsx not possible

### ISSUE THREAD

**Issue by robingarcia** [cnr-ibba/IMAGE-InjectTool#96]
Dear Sirs, 

we have downloaded the template file (xlsx format), but only UTF-8 or ASCII format is accepted for upload. 

How can we convert the template file from xlsx format to a text file with UTF-8?
The Template File contains several worksheets. 
Can more than one file be uploaded?

Best Robin

**Comment by bunop** [comment]
Dear @robingarcia ,
Thank you for using InjectTool. I Just find on the internet how to [convert a xlsx files into UTF8](https://help.surveygizmo.com/help/encode-an-excel-file-to-utf-8-or-utf-16). Briefly (for Windows Users):

1. Open your file 
2. Save As
3. Choose a position
4. Select "tools" dropdown menu, near the "Save" button
5. Choose "web options" from the menu
6. In the "encoding" tab, choose "Unicode (UTF-8)" in the "Save this document as" dropdown list
7. Save your file

If you have another OS system, please check the link I provided to you. Let me know if you are able to upload your template file into InjectTool.

All the best,

Paolo

**Comment by robingarcia** [comment]
Uhm. Upload worked. But we got this strange error again. Therefore we thought that the xlsx file had the wrong format.
Unfortunately I can't do anything with this error message. 


![image](https://user-images.githubusercontent.com/19394603/81665786-72ead880-9441-11ea-9513-ef1338df020f.png)

**Comment by bunop** [comment]
Well, you have misplaced columns value and you haven't set all the mandatory columns. 

- If you don't have information on `birth_location`, for example, the value `missing geographic information` should be provided in `birth_location_accuracy` column, since the last is *mandatory*. The same applies for the `collection_place` columns in sample sheet: if you don't have information, please keep such columns empty but please put `missing geographic information` in `collection_place_accuracy` column. 
- In the *sample* sheet you have to provide the `organism_part` column since is a mandatory field. 

If you fix all this stuff, you can upload your data with success. To reload your data, you could click on *Danger zone* -> *Reload datasource* and then upload the corrected file (maybe you are required to change the version). Or you can simple delete your submission and then create a new one with the correct file.

Fore more info on required fields, please check the [IMAGE-metadata](https://github.com/cnr-ibba/IMAGE-metadata) documentation
